import type { ComponentType } from "react";
import {
  AlertTriangle, Webhook, ArrowRight, Bell, Book, Library, Briefcase, Building, Landmark, Building2,
  Calculator, CalendarPlus, Banknote, Award, BarChartHorizontal, ChartBarDecreasing, Check, ChevronDown, ChevronUp,
  Clock, Cloud, CreditCard, Coins, Smartphone, BadgePercent, Edit, Eye, FilePenLine, ReceiptText, Gift, GitCompare,
  Handshake, Headset, Heart, HardHat, Lock, Mail, MapPin, MessageSquare, MessageCircle, Newspaper, CirclePlay, Puzzle,
  Receipt, ClipboardList, BarChartHorizontalBig, Rocket, Ruler, Search, Send, ShieldCheck, Signal, Sparkles, Star, Tag,
  Target, Wrench, TrendingUp, Truck, User, UserCheck, UserX, Users, UserRoundGroup, Video, Globe, X,
  type LucideProps,
} from "lucide-react";

// خريطة أسماء الأيقونات المستخدمة في الموقع إلى مكوّنات lucide-react المطابقة.
// لا تتطابق كل الأسماء حرفياً (lucide لا يملك أيقونات لبعض المفاهيم أو لشعارات العلامات التجارية)،
// لذا اخترنا أقرب بديل بصرياً لكل حالة.
const iconMap: Record<string, ComponentType<LucideProps>> = {
  "alert-triangle": AlertTriangle,
  api: Webhook,
  "arrow-right": ArrowRight,
  bell: Bell,
  book: Book,
  books: Library,
  "brand-whatsapp": MessageCircle,
  "brand-twitter": X,
  "brand-linkedin": Briefcase,
  briefcase: Briefcase,
  building: Building,
  "building-bank": Landmark,
  "building-community": Building2,
  "building-skyscraper": Building2,
  calculator: Calculator,
  "calendar-plus": CalendarPlus,
  cash: Banknote,
  certificate: Award,
  "chart-bar": BarChartHorizontal,
  "chart-off": ChartBarDecreasing,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  clock: Clock,
  cloud: Cloud,
  "credit-card": CreditCard,
  "currency-riyal": Coins,
  "device-mobile": Smartphone,
  discount: BadgePercent,
  edit: Edit,
  eye: Eye,
  "file-contract": FilePenLine,
  "file-invoice": ReceiptText,
  gift: Gift,
  "git-compare": GitCompare,
  handshake: Handshake,
  headset: Headset,
  heart: Heart,
  helmet: HardHat,
  lock: Lock,
  "lock-dollar": Lock,
  mail: Mail,
  "map-pin": MapPin,
  message: MessageSquare,
  "message-circle": MessageCircle,
  news: Newspaper,
  "player-play": CirclePlay,
  "puzzle-off": Puzzle,
  "receipt-2": Receipt,
  report: ClipboardList,
  "report-analytics": BarChartHorizontalBig,
  rocket: Rocket,
  "ruler-2": Ruler,
  search: Search,
  send: Send,
  "shield-check": ShieldCheck,
  signal: Signal,
  sparkles: Sparkles,
  star: Star,
  tag: Tag,
  target: Target,
  tools: Wrench,
  "trending-up": TrendingUp,
  truck: Truck,
  user: User,
  "user-check": UserCheck,
  "user-x": UserX,
  users: Users,
  "users-group": UserRoundGroup,
  video: Video,
  world: Globe,
  x: X,
};

export function Icon({ name, size = 20, ...props }: { name: string } & LucideProps) {
  const Component = iconMap[name];
  if (!Component) return null;
  return <Component size={size} {...props} />;
}
